// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";

export default function BirdHouse(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/BirdHouse3.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials["default"]} geometry={nodes?.House?.geometry} />
      <mesh material={materials["default"]} geometry={nodes?.Roof?.geometry} />
      <mesh
        material={materials["default"]}
        geometry={nodes?.SpeakerRim?.geometry}
      />
      <mesh
        material={materials["default"]}
        geometry={nodes?.SpeakerCentre?.geometry}
      />
      <mesh material={materials["default"]} geometry={nodes?.Base?.geometry} />
      <mesh material={materials["default"]} geometry={nodes?.Perch?.geometry} />
    </group>
  );
}
